// <auto-generated />
namespace Aula8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class atualizasao1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atualizasao1));
        
        string IMigrationMetadata.Id
        {
            get { return "202304120048142_atualizasao1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
